# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16-openj9-jre" do
  version "16.0.1+9"
  sha256 "320fde1b7acd2f13b2d7d55adb1e5c5bddb105f7ee3a35226d05a62e5f36a8f8"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jre/x64/mac/OpenJDK16U-jre_x64_mac_openj9_16.0.1_9_openj9-0.26.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16U-jre_x64_mac_openj9_16.0.1_9_openj9-0.26.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16-openj9.jre"
end