# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk12-openj9-jre-large" do
  version "12.0.2+10"
  sha256 "cd343a508263b1f7644bf3018ab659856af9e1fe348ab15f786e5e8854a7b80a"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/12/jre/x64/mac/OpenJDK12U-jre_x64_mac_openj9_macosXL_12.0.2_10_openj9-0.15.1.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK12 (OpenJ9) (JRE) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK12U-jre_x64_mac_openj9_macosXL_12.0.2_10_openj9-0.15.1.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.12-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.12-openj9.jre"
end