# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk14-openj9" do
  version "14.0.2+12"
  sha256 "8aad7e930d34244489a10149a4346cecd8484ca7f440f7916bb9ec1e43275c2b"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/14/jdk/x64/mac/OpenJDK14U-jdk_x64_mac_openj9_14.0.2_12_openj9-0.21.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK14 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK14U-jdk_x64_mac_openj9_14.0.2_12_openj9-0.21.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.14-openj9"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.14-openj9"
end