# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk11-jre" do
  version "11.0.13+8"
  sha256 "0f8d5500b5333699e6afc8b5a2689846f228ace6f85a1326dcbbc9e6ab8b209b"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jre/x64/mac/OpenJDK11U-jre_x64_mac_hotspot_11.0.13_8.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK11 (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK11U-jre_x64_mac_hotspot_11.0.13_8.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.11.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.11.jre"
end