# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16-jre" do
  version "16.0.1+9"
  sha256 "e1dca31bb02c2de72b0a3789a3a67336fd04ab6c720f127cae42fda0c789986f"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jre/x64/mac/OpenJDK16U-jre_x64_mac_hotspot_16.0.1_9.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16 (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16U-jre_x64_mac_hotspot_16.0.1_9.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16.jre"
end