# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16-openj9" do
  version "16.0.2+7"
  sha256 "151dfbf918682663e28187ed3b59b06e8c5c8ad39f57dada42612aa8290e8977"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/x64/mac/ibm-semeru-open-jdk_x64_mac_16.0.2_7_openj9-0.27.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jdk_x64_mac_16.0.2_7_openj9-0.27.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16-openj9.jdk"
end