# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk15" do
  version "15.0.1+9"
  sha256 "d69015c5ea7a1a81256f51cd33adf67e6f80c829d62651dd02067df3c452789b"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jdk/x64/mac/OpenJDK15U-jdk_x64_mac_hotspot_15.0.1_9.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK15"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK15U-jdk_x64_mac_hotspot_15.0.1_9.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.15.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.15.jdk"
end