# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16-openj9-jre" do
  version "16+36"
  sha256 "b2e0a6703089b9909a6de4f79f7e1e028be7b7af4a993bad9a2a845525f294bd"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jre/x64/mac/OpenJDK16-jre_x64_mac_openj9_16_36_openj9-0.25.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16-jre_x64_mac_openj9_16_36_openj9-0.25.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16-openj9.jre"
end