# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk13-openj9-jre-large" do
  version "13.0.2+8"
  sha256 "5da5f903d5fea5bc5ab207607820e4b2b91fc08588124bbe7393a77a1946748d"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jre/x64/mac/OpenJDK13U-jre_x64_mac_openj9_macosXL_13.0.2_8_openj9-0.18.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK13 (OpenJ9) (JRE) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK13U-jre_x64_mac_openj9_macosXL_13.0.2_8_openj9-0.18.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.13-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.13-openj9.jre"
end