# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk8-jre" do
  version "1.8.0_265-b01"
  sha256 "9a4bc2eeb784b6ff619c89d02d93b4ed52cc22a61406b26d8978abe61362c588"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/8/jre/x64/mac/OpenJDK8U-jre_x64_mac_hotspot_8u265b01.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK8 (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK8U-jre_x64_mac_hotspot_8u265b01.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.8.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.8.jre"
end