# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16-openj9-jre" do
  version "16.0.2+7"
  sha256 "7667c41f2b88740f500396da5fa84682f915295a0972bf7b520e45529489610a"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jre/x64/mac/ibm-semeru-open-jre_x64_mac_16.0.2_7_openj9-0.27.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jre_x64_mac_16.0.2_7_openj9-0.27.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16-openj9.jre"
end