# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17" do
  version "17.0.1+12"
  sha256 "6318bac0268115f5740abc0113026356c3d784169ef9c5c94df2c3e3744505de"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/x64/mac/OpenJDK17U-jdk_x64_mac_hotspot_17.0.1_12.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK17U-jdk_x64_mac_hotspot_17.0.1_12.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17.jdk"
end