# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk8-openj9-jre-large" do
  version "1.8.0_275-b01"
  sha256 "132af2c0d2fbfcc079081cfee15c337bab236ff177a826fb8cef12410d76f9f2"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/8/jre/x64/mac/OpenJDK8U-jre_x64_mac_openj9_macosXL_8u275b01_openj9-0.23.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK8 (OpenJ9) (JRE) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK8U-jre_x64_mac_openj9_macosXL_8u275b01_openj9-0.23.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.8-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.8-openj9.jre"
end