# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk15-openj9-jre-large" do
  version "15+36"
  sha256 "4ba9adc3c8847e69428ec555eec82b934da08283fbe893a74448c3fcbe37df8a"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jre/x64/mac/OpenJDK15U-jre_x64_mac_openj9_macosXL_15_36_openj9-0.22.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK15 (OpenJ9) (JRE) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK15U-jre_x64_mac_openj9_macosXL_15_36_openj9-0.22.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.15-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.15-openj9.jre"
end