# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk13-openj9-large" do
  version "13.0.2+8"
  sha256 "473331187eab4b113abb5f5267b75d248521f252931a372ec25e63f729dbab03"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jdk/x64/mac/OpenJDK13U-jdk_x64_mac_openj9_macosXL_13.0.2_8_openj9-0.18.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK13 (OpenJ9) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK13U-jdk_x64_mac_openj9_macosXL_13.0.2_8_openj9-0.18.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.13-openj9"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.13-openj9"
end