# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk14-openj9-jre-large" do
  version "14.0.2+12"
  sha256 "77239479d45c428eaa921da8362cd853aacac44d38c39eb68c286fe63532a98e"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/14/jre/x64/mac/OpenJDK14U-jre_x64_mac_openj9_macosXL_14.0.2_12_openj9-0.21.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK14 (OpenJ9) (JRE) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK14U-jre_x64_mac_openj9_macosXL_14.0.2_12_openj9-0.21.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.14-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.14-openj9.jre"
end