# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk8-openj9" do
  version "1.8.0_332-b09"
  sha256 "3a8e720aa1b14bd39ee5a16a46215b17bba43e4734e6c7e373204553e13360f2"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/8/jdk/x64/mac/ibm-semeru-open-jdk_x64_mac_8u332b09_openj9-0.32.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK8 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jdk_x64_mac_8u332b09_openj9-0.32.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.8-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.8-openj9.jdk"
end