# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk15-openj9-jre" do
  version "15.0.2+7"
  sha256 "ea6da5d56bbc14c272321442271bbd05cb76686b410af621a13bfc7db79dc4d6"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jre/x64/mac/OpenJDK15U-jre_x64_mac_openj9_15.0.2_7_openj9-0.24.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK15 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK15U-jre_x64_mac_openj9_15.0.2_7_openj9-0.24.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.15-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.15-openj9.jre"
end