# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16" do
  version "16.0.2+7"
  sha256 "3348e66ae287c70e48935d435b62cc6dec65558f84e6d60ac283dbb78f81ef7d"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/x64/mac/OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16.jdk"
end