# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk15-openj9" do
  version "15.0.2+7"
  sha256 "3c8027cc21b1cfaf0aa2c75f2af55a940cd4f530945f45e02730d68f631fa9c4"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jdk/x64/mac/OpenJDK15U-jdk_x64_mac_openj9_15.0.2_7_openj9-0.24.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK15 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK15U-jdk_x64_mac_openj9_15.0.2_7_openj9-0.24.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.15-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.15-openj9.jdk"
end