# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk12-openj9-large" do
  version "12.0.2+10"
  sha256 "ab8456a3784edadcf3ff4d20f7482218648b8ec1a70ab5164a25ba9030abc1fc"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/12/jdk/x64/mac/OpenJDK12U-jdk_x64_mac_openj9_macosXL_12.0.2_10_openj9-0.15.1.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK12 (OpenJ9) (XL)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK12U-jdk_x64_mac_openj9_macosXL_12.0.2_10_openj9-0.15.1.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.12-openj9"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.12-openj9"
end