# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk11-openj9-jre" do
  version "11.0.15+10"
  sha256 "17a5cd6305ad8a9ab2331ab1143e3e9f6a08fe29da5cb213f3278e4857d02374"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jre/x64/mac/ibm-semeru-open-jre_x64_mac_11.0.15_10_openj9-0.32.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK11 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jre_x64_mac_11.0.15_10_openj9-0.32.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.11-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.11-openj9.jre"
end