# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16" do
  version "16.0.1+9"
  sha256 "7308a15d054d07d504f616416b3622d153c3cc63906441a5730ca1f9d4a43854"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/x64/mac/OpenJDK16U-jdk_x64_mac_hotspot_16.0.1_9.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16U-jdk_x64_mac_hotspot_16.0.1_9.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16.jdk"
end