# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17-openj9" do
  version "17.0.3+7"
  sha256 "b1ec52ddf116be15be70fc30565c5635cf9dc0d3ec1344e1d0383ebf3e1460d7"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/x64/mac/ibm-semeru-open-jdk_x64_mac_17.0.3_7_openj9-0.32.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jdk_x64_mac_17.0.3_7_openj9-0.32.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17-openj9.jdk"
end