# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17" do
  version "17.0.3+7"
  sha256 "70afd9b4f76d69a5f9ab3f740a9289f41d23558f02b133e684c80380c265455f"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/x64/mac/OpenJDK17U-jdk_x64_mac_hotspot_17.0.3_7.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK17U-jdk_x64_mac_hotspot_17.0.3_7.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17.jdk"
end