# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk16" do
  version "16+36"
  sha256 "2d101b7bc4901c1a9554ba158b9eb4bf245b6dc314bd82078b1c9b85953ae5ae"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/x64/mac/OpenJDK16-jdk_x64_mac_hotspot_16_36.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK16"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK16-jdk_x64_mac_hotspot_16_36.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.16.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.16.jdk"
end