# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17-jre" do
  version "17.0.3+7"
  sha256 "1ee827ad363227dbfb592f0225cb27c16d35c64690decd66cdf3540450258f68"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jre/x64/mac/OpenJDK17U-jre_x64_mac_hotspot_17.0.3_7.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17 (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK17U-jre_x64_mac_hotspot_17.0.3_7.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17.jre"
end