# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk13-openj9" do
  version "13.0.2+8"
  sha256 "898ee58905a332f15678c6f687652d062954f8b77fad6f427df19614f49ce418"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jdk/x64/mac/OpenJDK13U-jdk_x64_mac_openj9_13.0.2_8_openj9-0.18.0.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK13 (OpenJ9)"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK13U-jdk_x64_mac_openj9_13.0.2_8_openj9-0.18.0.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.13-openj9.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.13-openj9.jdk"
end