# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk11-openj9-jre" do
  version "11.0.14.1+1"
  sha256 "3f972291247d31adc5414fa0b5b149b8ed870083540fc89f3a418a61b08677f1"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jre/x64/mac/ibm-semeru-open-jre_x64_mac_11.0.14.1_1_openj9-0.30.1.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK11 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jre_x64_mac_11.0.14.1_1_openj9-0.30.1.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.11-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.11-openj9.jre"
end