# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17-openj9-jre" do
  version "17.0.1+12"
  sha256 "73cda0a59f9c508cc2fda7a6ac1c8dd88d66fcfae6495214b2640bf793c5691f"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jre/x64/mac/ibm-semeru-open-jre_x64_mac_17.0.1_12_openj9-0.29.1.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17 (OpenJ9) (JRE)"
  homepage "https://adoptopenjdk.net/"

  pkg "ibm-semeru-open-jre_x64_mac_17.0.1_12_openj9-0.29.1.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17-openj9.jre"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17-openj9.jre"
end