# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "tuna-adoptopenjdk17" do
  version "17.0.2+8"
  sha256 "b82d3ba3ff4c453bd954979a20e67754478294da8650e3b9e50f6d1a7cf5c628"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/x64/mac/OpenJDK17U-jdk_x64_mac_hotspot_17.0.2_8.pkg"
  appcast "https://github.com/AdoptOpenJDK"
  name "AdoptOpenJDK17"
  homepage "https://adoptopenjdk.net/"

  pkg "OpenJDK17U-jdk_x64_mac_hotspot_17.0.2_8.pkg"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "net.adoptopenjdk.17.jdk"], print_stdout: true
  end

  uninstall pkgutil: "net.adoptopenjdk.17.jdk"
end