# PLEASE DO NOT EDIT THIS FILE. EDIT Templates/adoptopenjdk.rb.tmpl
cask "{cask_name}" do
  version "{version}"
  sha256 "{sha256}"

  # github.com/AdoptOpenJDK was verified as official when first introduced to the cask
  url "{url}"
  appcast "https://github.com/AdoptOpenJDK"
  name "{name}"
  homepage "https://adoptopenjdk.net/"

  pkg "{filename}"

  postflight do
    system_command "/usr/sbin/pkgutil", args: ["--pkg-info", "{identifier}"], print_stdout: true
  end

  uninstall pkgutil: "{identifier}"
end