name: PULL-REQUEST-CI

on:
  push:
    branches:
    - update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
